### ISSUE TITLE
Generating a Blank Image in Safari Browser

### ISSUE THREAD

**Issue by ahmedjamshed** [bubkoo/html-to-image#199]
This package is generating a blank image in the Safari browser but it's working good in Chrome and Firefox

### Expected Behavior

It should work as good in Safari as well, as it is working on Chrome and Firefox

### Current Behavior

Generating a blank image in Safari 

### Your Environment

- html-to-image: 1.9.0
- OS: Big SUR (M1 Macbook)
- Browser: Safari 14.1.2 

### Code

```
  const onSaveClick = async () => {
    try {
      const avatar = document.querySelector("#avatar") as HTMLElement;
      const image = document.querySelector(".traitLayer") as HTMLElement;
      if (avatar === null) {
        return
      }
      const imageConfig = {
        cacheBust: true, pixelRatio: 1, height: image.clientHeight, quality: 0.98,
        width: image.clientWidth, canvasWidth: 3000, canvasHeight: 3000,
      }
      const dataUrl = await toPng(avatar, imageConfig)
      const link = document.createElement('a')
      link.download = 'Avatar.png'
      link.href = dataUrl
      link.click()

    }  catch (err: any) {
      // Nothing here
    }
  }
```

**Comment by mahen23** [comment]
I had similar problems on ionic. Then used setTimeout with a delay of 2,000 milliseconds. My images are now generating fine.

**Comment by AMandujano-BI** [comment]
Same problem here.

**Comment by khojabergen** [comment]
Same problem

**Comment by mrhieu** [comment]
After specifying `width` and `height` attributes of the `img` tag, the issue has gone. You guys can try that.

**Comment by imbarwinata** [comment]
Same problem

**Comment by pranavatoito** [comment]
same problem for me too.

**Comment by GeekyADAMS** [comment]
This works for me:


https://github.com/bubkoo/html-to-image/issues/214#issuecomment-1002640937

**Comment by GeekyADAMS** [comment]
Well, as far as I can tell, this is the best solution for now. The problem is that IOS and MacOS find it hard to “paint” the details of an html content when converting to any image format. You would think that adding enough delay to make sure content is fully rendered would solve the problem but it doesn’t, what works is attempting conversion multiple times in a chain, to make sure it captures all the details.

So depending on the level of details in your content, you might need to increase the number of conversion chains and maybe add a lil bit more delay. Maybe a sane thing to do is to create that detect IOS and MacOS devices and then take in a number for how many repeated conversion attempts you want depending on the details of your content to make sure it works every time.

As a matter of fact, this can be demoed manually by attempting one conversion and download process after another and see how the level of details captured increases.

Maybe the library maintainer can incorporate this in a fix release.

**Comment by hlmartin** [comment]
Building off what @vince760 and @GeekyADAMS posted, I came up with this solution which will check the top left and bottom right pixels and retry until they differ. Obviously, this works best when the image you are rendering doesn't have solid colours around the outside, however if you adjust the max attempts you might be able to catch this without wasting too much time.

```
function safariDownload(attempts) {
  const element = document.getElementById('Element you are wanting to download');
  htmlToImage.toCanvas(element).then(function(canvas) {
    const context = canvas.getContext('2d');
    const imageData = context.getImageData(0, 0, canvas.width, canvas.height);
    if (!pixelsAreEqual(imageData) || attempts >= 10) {
    canvas.id = *Give your canvas an ID*;
    document.body.appendChild(canvas);
    canvasToImage('Name of the canvas ID you assigned on canvas.id', {
       name: `Name you want given to the image hen downloaded`,
       type: 'png',
       quality: 1,
     });
     document.body.removeChild(canvas);
    } else {
      console.log(`Trying Safari rendering again (attempt #${attempts + 1})...`);
      setTimeout(() => (safariDownload(card, options, attempts + 1)), 1000);
    }
  });
}

function pixelsAreEqual(imageData) {
  const len = imageData.data.length;
  const topLeftPixelRgba = [imageData.data[0], imageData.data[1], imageData.data[2], imageData.data[3]];
  const bottomRightPixelRgba = [imageData.data[len - 4], imageData.data[len - 3], imageData.data[len - 2], imageData.data[len - 1]];
  return (topLeftPixelRgba.every((v,i)=> v === bottomRightPixelRgba[i]));
}
```
