### ISSUE TITLE
SVG with image not working in Safari

### ISSUE THREAD

**Issue by MartinPelijak** [bubkoo/html-to-image#214]
Hi, i am using your incredible library but i have a problem.
I want to convert a SVG with an image inside into a png. In Firefox and Chrome everything works perfect, but in Safari the conversion is ignoring the image inside the SVG.

Here is a codepen (the face is the image) https://codepen.io/RainPara/pen/MWvqZNz

Environment: 
IPhone 11 with ios 15

**Comment by imbarwinata** [comment]
Same problem

**Comment by GeekyADAMS** [comment]
Apparently, the fix is to do a redundant chaining as it takes a little time for IOS to capture the whole data.

This worked for me:

 htmlToImage.toJpeg(document.getElementById('template'), { quality: 1 })
        .then(() => {
          htmlToImage.toJpeg(document.getElementById('template'), { quality: 1 })
          .then(() => {
            htmlToImage.toJpeg(document.getElementById('template'), { quality: 1 })
            .then((dataUrl) => {
              const link = document.createElement('a');
              link.download = 'name.jpeg';
              link.href = dataUrl;
              link.click();
            })
          })
        })
        .catch((error) => {
          console.error('oops, something went wrong!', error);
          alert('Ooops! Something went wrong. Try again.');
        });

      }, 1500);
      
      Change toJpeg to toSVG or any other format

**Comment by Matt-Pilott** [comment]
@GeekyADAMS i found your workaround does work mostly, but not always. Be good to get a proper solution on this!

**Comment by GeekyADAMS** [comment]
Well, as far as I can tell, this is the best solution for now. The problem is that IOS and MacOS find it hard to “paint” the details of an html content when converting to any image format. You would think that adding enough delay to make sure content is fully rendered would solve the problem but it doesn’t, what works is attempting conversion multiple times in a chain, to make sure it captures all the details.

So depending on the level of details in your content, you might need to increase the number of conversion chains and maybe add a lil bit more delay. Maybe a sane thing to do is to create that detect IOS and MacOS devices and then take in a number for how many repeated conversion attempts you want depending on the details of your content to make sure it works every time.

As a matter of fact, this can be demoed manually by attempting one conversion and download process after another and see how the level of details captured increases.

Maybe the library maintainer can incorporate this in a fix release.

**Comment by mattpilott** [comment]
This is still an issue

**Comment by Yhozen** [comment]
> This is still an issue

Can confirm

**Comment by TiagoSilvaPereira** [comment]
I had a similar issue using this library with Electron 12 on Linux (works well on Windows)

**Comment by Aakash-suthar** [comment]
Still there is issue for safari. Not able to download the image properly. Some icons are not visible. Help if anyone has fixed the issue or the solution is working for Safari browser?

**Comment by johnkorzhuk** [comment]
I was able to solve this issue by using the [toBlob](https://www.npmjs.com/package/html-to-image#toBlob) function in conjunction with [file-saver](https://github.com/eligrey/FileSaver.js/).

**Comment by kurzenkov-globant** [comment]
I found this solution, working for me
```
const element = document.getElementById('template');
const imageSettings = { quality: 1 };

  const url = await htmlToImage.toJpeg(element, imageSettings);

  let img = document.createElement('img');
  img.src = url;

  const image = await new Promise((resolve) => {
    img.onload = () => {
      htmlToImage.toJpeg(element, imageSettings).then((dataUrl) => {
        resolve(dataUrl);
      });
    };
  });

  return image;
```

**Comment by valentinbdv** [comment]
The @kurzenkov-globant solution works perfectly. Thanks

**Comment by paas10** [comment]
This is still an issue

**Comment by tarjep** [comment]
I am also encountering this issue.

**Comment by NicoADavite** [comment]
please reopen

**Comment by gschattenhofer** [comment]
Still an issue

**Comment by nazreen** [comment]
still an isue

**Comment by danny-dang** [comment]
I fixed by adding some wait time before downloading the image:
```
      const url = await toPng(domElement);

      const link = document.createElement('a');
      
      await sleep(500)
      
      link.href = url;
      link.download = filename;

      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
```


Another fix is changing to another library [modern-screenshot](https://github.com/qq15725/modern-screenshot) which is a fork of `html-to-image`.
