### ISSUE TITLE
why add this breaking chang in this version

### ISSUE THREAD

**Issue by mochen666** [bubkoo/html-to-image#365]
![image](https://user-images.githubusercontent.com/13551778/215699394-e3779297-85ac-43dd-9bc2-eee1b707bf2c.png)

**Comment by bubkoo** [comment]
@mochen666 Why it's a breaking chang?

**Comment by TouqeerH** [comment]
> @mochen666 Why it's a breaking change?

This change is breaking `yarn`. As it requires `pnpm` which many of us do not use.

**Comment by Fawwad-Khan** [comment]
Also facing the same issue.

**Comment by txemaleon** [comment]
Hi!

Also facing this

The problem is your `pre-install` hook is running `npx only-allow pnpm` which breaks installs on packages dependant on `html-to-image`.

While I understand this is good intentioned, I'd appreciate if you could revert the change in the `pre-install` hook, as it is not needed after publishing the package and it's effectively prohibiting the installation in every non-pnpm environment.

Thanks! Hope this helps you

**Comment by thealonekhan** [comment]
Facing same issue

**Comment by carlosg-ordering** [comment]
Same here

**Comment by chrislondon** [comment]
same here

**Comment by ddelpiano** [comment]
same here

**Comment by sandi-buchanan** [comment]
Same issue being encountered in our project.

**Comment by txemaleon** [comment]
If anyone gets here trough google, you have to update to v`1.11.10` at least to fix this problema

**Comment by bubkoo** [comment]
v1.11.9 was marked as deprecated.

![image](https://user-images.githubusercontent.com/6045824/216217166-aae50568-ba4f-4163-9f1b-40b4a73fbef3.png)
