### ISSUE TITLE
Cuts off bottom on high resolution screens

### ISSUE THREAD

**Issue by tyjoti89** [bubkoo/html-to-image#9]
When running .toBlob(node) on a 3840x2160 resolution monitor, the bottom of the node element is cropped off the picture. I can drag the application (browser tab) onto one of my 1920x1080 monitors and it works as expected.

**Comment by curiousPup** [comment]
same problem

**Comment by leopoldkristjansson** [comment]
I was experiencing this too. Adding a 1px padding to the target node worked for me. Hacky, but I still wanted to point it out since it worked in my case.

**Comment by smeijer** [comment]
This issue ain't fixed, so I recommend reopening the issue.

I also kindly want to ask to reconsider having stalebot close inactive issues. 

I see not adding more useless issue comments as a sign of respect to the busy life of maintainers. Not commenting `+1` or `still a problem` doesn't mean the problem doesn't exist any more. It means we know someone is working on it, or other issues have higher priorities.

Having stalebot close the issues, motivates people to add those useless `+1` comments, because the issues need activity to not get closed.

Yes, closing issues reduce the ticket count on short term. But what's the worth of hiding issues, that are still not truly resolved? Milestones or even projects can be used to prioritize. And issues that won't ever be fixed, can be labeled as `won't fix` or `invalid`. Which is a human decision, and is totally fine.
